### ISSUE TITLE
VSIX Size Too Large for Marketplace Upload

### ISSUE THREAD

**Issue by charleszipp** [charleszipp/azure-pipelines-tasks-terraform#8]
## Description
The packaged vsix to be distributed for the marketplace exceeds the marketplace file size limit. This is due to the vsix containing several files and folders that are not needed for task execution
- node_modules ?
- source map files
- readme
- .nyc_output
_ .test-output
- coverage
- .env-sample
- package.json ?
- package-lock.json ?
- tsconfig.json
- src
- .bin/tests

The vsix should be packaged using only the files essential for task execution so that the vsix easily fits within the marketplace file size limits

## Justification
VSIX cannot be uploaded to marketplace until this is resolved. This is blocking publishing other features that have been completed.

**Comment by dcopl** [comment]
I see node modules listed here as not being needed for task execution. Getting the following error when I tried to use the module today. Seems like this could be related.

`2018-11-22T09:39:55.2097868Z ##[debug]Evaluating condition for step: 'Use Terraform 0.11.8'
2018-11-22T09:39:55.2099072Z ##[debug]Evaluating: succeeded()
2018-11-22T09:39:55.2099396Z ##[debug]Evaluating succeeded:
2018-11-22T09:39:55.2099866Z ##[debug]=> True
2018-11-22T09:39:55.2100298Z ##[debug]Result: True
2018-11-22T09:39:55.2100684Z ##[section]Starting: Use Terraform 0.11.8
2018-11-22T09:39:55.2103599Z ==============================================================================
2018-11-22T09:39:55.2103782Z Task         : Terraform Installer
2018-11-22T09:39:55.2103874Z Description  : Installs a specific version of terraform
2018-11-22T09:39:55.2104165Z Version      : 0.2.3
2018-11-22T09:39:55.2104246Z Author       : Charles Zipp
2018-11-22T09:39:55.2104714Z Help         : 
2018-11-22T09:39:55.2104866Z ==============================================================================
2018-11-22T09:39:57.2695221Z module.js:471
2018-11-22T09:39:57.2695565Z     throw err;
2018-11-22T09:39:57.2695691Z     ^
2018-11-22T09:39:57.2695735Z 
2018-11-22T09:39:57.2696568Z Error: Cannot find module 'vsts-task-lib/task'
2018-11-22T09:39:57.2696735Z     at Function.Module._resolveFilename (module.js:469:15)
2018-11-22T09:39:57.2696874Z     at Function.Module._load (module.js:417:25)
2018-11-22T09:39:57.2696963Z     at Module.require (module.js:497:17)
2018-11-22T09:39:57.2697086Z     at require (internal/module.js:20:19)
2018-11-22T09:39:57.2697514Z     at Object.<anonymous> (/home/vsts/work/_tasks/TerraformInstaller_11645770-d18e-11e8-8f5b-1b8b62612b3b/0.2.3/.bin/index.js:18:15)
2018-11-22T09:39:57.2697700Z     at Module._compile (module.js:570:32)
2018-11-22T09:39:57.2697863Z     at Object.Module._extensions..js (module.js:579:10)
2018-11-22T09:39:57.2697954Z     at Module.load (module.js:487:32)
2018-11-22T09:39:57.2698309Z     at tryModuleLoad (module.js:446:12)
2018-11-22T09:39:57.2698535Z     at Function.Module._load (module.js:438:3)
2018-11-22T09:39:57.2839091Z ##[section]Finishing: Use Terraform 0.11.8`

**Comment by charleszipp** [comment]
@dcopl to work around this issue for now, leave out the terraform install task. It looks like you are using a Linux build agent. The hosted Ubuntu agents come with terraform (0.11.8 last I checked) installed. I believe this is a separate issue. I'll open a new issue and get this resolved.

Thanks for reporting this!

**Comment by charleszipp** [comment]
@dcopl I have reverted this change and republished as version 0.2.4. I will get a more permanent fix implemented after the thanksgiving holiday

**Comment by dcopl** [comment]
@charleszipp Hey Charles, came back to this now. Can confirm the tasks work again.

**Comment by charleszipp** [comment]
@dcopl this is not fixed. I am still finding issues with bundling the azure-pipelines-task-lib with webpack since its a stateful module. I have unpublished the package for now until I am able to get this resolved. I am on vacation this week so it will likely be next week before i have a chance to get this solved
